### ISSUE TITLE
Custom exe as payload

### ISSUE THREAD

**Issue by Thepowa753** [youhacker55/PayGen#1]
Is it possible to use my custom exe as payload? 
Need to pentest and bypassing my client antivirus

**Comment by Thepowa753** [comment]
Finded the way:
`python3 signer-exe.py  www.microsoft.com 443 yourExe.exe signed.exe`

**Comment by TheNewAttacker64** [comment]
This is exesigner  it will not bypass av but some modules you can use with your own exe hta like the hta attack and the vbs dropper 
you can check tuto on my fb page
